package emit

import (
	"fmt"
	"sort"

	"gopkg.in/yaml.v3"

	"github.com/paulxiep/caravan/internal/compiler"
)

// EmitFargateBuildOverride emits a docker-compose file containing one
// `build:`-only service per Lambda seam in the target. caravan up uses
// `docker compose -f <base> -f <this> build <lambda-service>` to build
// each Lambda image, then tags + pushes to ECR.
//
// Why exists: regular Fargate entries get their build config from the
// user's hand-authored base compose (one service per entry; the user
// owns it). Lambda images are a caravan invention — slim Dockerfile
// stage selected via `seam.image_target:`, per-seam ECR tag
// `lambda-<seam>` — so caravan owns the build spec. The override
// inherits the host entry's context + additional_contexts from base
// compose, but overrides `target:` and adds `args.CARAVAN_TARGET`.
//
// Service name convention: `<seam-dashed>-lambda` (e.g.
// `validate-extraction-lambda`). Local image after build:
// `<project>-<seam-dashed>-lambda:latest` — caller renames to
// `<host-entry-repo>:lambda-<seam-dashed>` for the ECR push.
//
// Returns nil bytes + nil error when the target has no Lambda seams
// (no override needed). Callers check len(body) > 0 before writing.
func EmitFargateBuildOverride(
	rp *compiler.ResolvedPlan,
	baseBuilds map[string]*BaseComposeBuild,
) ([]byte, error) {
	if rp == nil || rp.Plan == nil {
		return nil, fmt.Errorf("nil ResolvedPlan")
	}
	target := rp.Plan.Targets[rp.TargetName]
	if target == nil {
		return nil, fmt.Errorf("target %q not in plan", rp.TargetName)
	}
	if target.Runtime != compiler.RuntimeFargate {
		return nil, nil
	}

	lambdaSeamNames := make([]string, 0)
	for name, mode := range target.Seams {
		if mode == compiler.SeamLambda {
			lambdaSeamNames = append(lambdaSeamNames, name)
		}
	}
	if len(lambdaSeamNames) == 0 {
		return nil, nil
	}
	sort.Strings(lambdaSeamNames)

	root := &yaml.Node{Kind: yaml.MappingNode}
	services := &yaml.Node{Kind: yaml.MappingNode}
	root.Content = append(root.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "services"},
		services,
	)

	for _, seamName := range lambdaSeamNames {
		seam := rp.Plan.Seams[seamName]
		if seam == nil {
			return nil, fmt.Errorf("seam %q referenced by target.Seams but missing from plan", seamName)
		}
		host := lambdaHostEntryByPath(rp.Plan, seam)
		if host == nil {
			return nil, fmt.Errorf("Lambda seam %q: cannot find host entry by path %q", seamName, seam.Path)
		}
		hostBuild := baseBuilds[host.Name]
		if hostBuild == nil {
			return nil, fmt.Errorf("Lambda seam %q: host entry %q has no `build:` block in base compose; caravan needs context + dockerfile + additional_contexts from the base to emit the Lambda build override", seamName, host.Name)
		}
		serviceName := DashedSeamName(seamName) + "-lambda"
		stageTarget := seam.ImageTarget
		if stageTarget == "" {
			stageTarget = host.RuntimeTarget
		}

		svc := buildLambdaServiceNode(hostBuild, stageTarget, rp.TargetName)
		services.Content = append(services.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: serviceName},
			svc,
		)
	}

	out := &yaml.Node{Kind: yaml.DocumentNode, Content: []*yaml.Node{root}}
	body, err := yaml.Marshal(out)
	if err != nil {
		return nil, fmt.Errorf("EmitFargateBuildOverride: marshal: %w", err)
	}
	header := "# Generated by `caravan compile --target=" + target.Name + "`. Do not edit by hand.\n" +
		"# Build-only override for Lambda peer images. Layered with the base compose:\n" +
		"#   docker compose -f <base> -f docker-compose.fargate-build.generated.yaml build <seam>-lambda\n\n"
	return append([]byte(header), body...), nil
}

func buildLambdaServiceNode(
	host *BaseComposeBuild,
	stageTarget, caravanTarget string,
) *yaml.Node {
	build := &yaml.Node{Kind: yaml.MappingNode}
	if host.Context != "" {
		build.Content = append(build.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "context"},
			&yaml.Node{Kind: yaml.ScalarNode, Value: host.Context},
		)
	}
	if host.Dockerfile != "" {
		build.Content = append(build.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "dockerfile"},
			&yaml.Node{Kind: yaml.ScalarNode, Value: host.Dockerfile},
		)
	}
	if stageTarget != "" {
		build.Content = append(build.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "target"},
			&yaml.Node{Kind: yaml.ScalarNode, Value: stageTarget},
		)
	}
	// args.CARAVAN_TARGET — multi-stage Dockerfiles read this to template
	// `infra/${CARAVAN_TARGET}/...` COPY paths consistently across stages.
	argsNode := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		{Kind: yaml.ScalarNode, Value: "CARAVAN_TARGET"},
		{Kind: yaml.ScalarNode, Value: caravanTarget},
	}}
	build.Content = append(build.Content,
		&yaml.Node{Kind: yaml.ScalarNode, Value: "args"},
		argsNode,
	)
	// additional_contexts copied from base compose's host entry, so the
	// Lambda image gets the same `caravan-rpc-src` (or other named contexts)
	// the host entry's regular build uses.
	if len(host.AdditionalContexts) > 0 {
		acNode := &yaml.Node{Kind: yaml.MappingNode}
		acKeys := make([]string, 0, len(host.AdditionalContexts))
		for k := range host.AdditionalContexts {
			acKeys = append(acKeys, k)
		}
		sort.Strings(acKeys)
		for _, k := range acKeys {
			acNode.Content = append(acNode.Content,
				&yaml.Node{Kind: yaml.ScalarNode, Value: k},
				&yaml.Node{Kind: yaml.ScalarNode, Value: host.AdditionalContexts[k]},
			)
		}
		build.Content = append(build.Content,
			&yaml.Node{Kind: yaml.ScalarNode, Value: "additional_contexts"},
			acNode,
		)
	}

	svc := &yaml.Node{Kind: yaml.MappingNode, Content: []*yaml.Node{
		{Kind: yaml.ScalarNode, Value: "build"},
		build,
	}}
	return svc
}

// lambdaHostEntryByPath mirrors compute_lambda.go's lambdaHostEntry but
// without crossing the hcl/emit package import boundary. Returns the
// alphabetically-first container-mode entry whose `path:` equals the
// seam's path; fallback to first container entry when seam.Path is
// empty (single-entry repos with defaultSeamPaths in effect).
func lambdaHostEntryByPath(plan *compiler.Plan, seam *compiler.Seam) *compiler.Entry {
	if plan == nil || seam == nil {
		return nil
	}
	names := make([]string, 0, len(plan.Entries))
	for n := range plan.Entries {
		names = append(names, n)
	}
	sort.Strings(names)
	if seam.Path != "" {
		for _, n := range names {
			e := plan.Entries[n]
			if e != nil && e.Path == seam.Path {
				return e
			}
		}
	}
	for _, n := range names {
		if e := plan.Entries[n]; e != nil {
			return e
		}
	}
	return nil
}

// DashedSeamName mirrors hcl/naming.go's toDashed for seam-derived
// identifiers — lowercase + `_` → `-`. Exported so cmd/caravan/up.go
// can reuse the same dashing when forming docker tag commands; the
// resulting string must match what compute_lambda.go's HCL emits as
// the Lambda image tag suffix (`lambda-<DashedSeamName(seam.Name)>`).
func DashedSeamName(s string) string {
	out := ""
	for _, r := range s {
		switch {
		case r >= 'A' && r <= 'Z':
			out += string(r - 'A' + 'a')
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			out += string(r)
		case r == '_':
			out += "-"
		}
	}
	return out
}
