package emit

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/paulxiep/caravan/internal/compiler"
)

// EmitEnvTemplate writes a `.env.template` next to the HCL files. The
// template names every variable the user must populate before
// `docker compose up`, with the matching `tofu output -json | jq -r ...`
// snippet inline so the user can copy/paste.
//
// One-shot dance from the template (also documented in README.md):
//
//	tofu -chdir=<outDir> output -json |
//	  jq -r 'to_entries | map("\(.key)=\(.value.value)") | .[]' > <outDir>/.env.hybrid
//	docker compose ... --env-file <outDir>/.env.hybrid up
//
// Only fires for hybrid-dev targets. Returns the path written.
func EmitEnvTemplate(rp *compiler.ResolvedPlan, outDir string) (string, error) {
	if rp == nil || rp.Plan == nil {
		return "", fmt.Errorf("nil ResolvedPlan")
	}
	target := rp.Plan.Targets[rp.TargetName]
	if target == nil || !target.CredsPassthrough {
		return "", nil
	}

	// Collect all unique env var keys that consumer entries see via
	// resource_endpoint vars. These are the keys the compose override
	// references as `${VAR}` — they must end up in the .env file.
	keys := map[string]struct{}{}
	for _, env := range rp.ResourceEnvVars {
		for k, v := range env {
			if strings.HasPrefix(v, "${") {
				keys[k] = struct{}{}
			}
		}
	}
	if len(keys) == 0 {
		return "", nil
	}
	sorted := make([]string, 0, len(keys))
	for k := range keys {
		sorted = append(sorted, k)
	}
	sort.Strings(sorted)

	var body strings.Builder
	body.WriteString("# Generated by `caravan compile --target=" + target.Name + "`. Do not commit.\n")
	body.WriteString("# Populate by running:\n")
	body.WriteString("#\n")
	body.WriteString("#   tofu -chdir=. output -json | \\\n")
	body.WriteString("#     jq -r 'to_entries | map(\"\\(.key)=\\(.value.value)\") | .[]' > .env.hybrid\n")
	body.WriteString("#\n")
	body.WriteString("# then layer the compose override with `--env-file .env.hybrid`.\n\n")
	for _, k := range sorted {
		body.WriteString(k)
		body.WriteString("=\n")
	}

	path := filepath.Join(outDir, ".env.template")
	if err := os.WriteFile(path, []byte(body.String()), 0o644); err != nil {
		return "", fmt.Errorf("EmitEnvTemplate write: %w", err)
	}
	return path, nil
}

// EmitHybridReadme writes a README.md in outDir with the 3-step run
// instructions for hybrid-dev mode. Lands next to the generated HCL +
// compose override so the user finds it when they cd into outDir.
func EmitHybridReadme(rp *compiler.ResolvedPlan, outDir, repoRelativeOutDir string) (string, error) {
	if rp == nil || rp.Plan == nil {
		return "", fmt.Errorf("nil ResolvedPlan")
	}
	target := rp.Plan.Targets[rp.TargetName]
	if target == nil || !target.CredsPassthrough {
		return "", nil
	}

	envCmd := "tofu -chdir=. output -json | \\\n" +
		"  jq -r 'to_entries | map(\"\\(.key)=\\(.value.value)\") | .[]' > .env.hybrid"

	// The README is read by humans running shell commands; emit forward
	// slashes for cross-shell compatibility (Windows native `\` breaks
	// bash / Git Bash quoting on Windows).
	repoRelativeOutDir = filepath.ToSlash(repoRelativeOutDir)

	var body strings.Builder
	body.WriteString("# Caravan hybrid-dev target — " + rp.Plan.Name + " / " + target.Name + "\n\n")
	body.WriteString("Generated by `caravan compile --target=" + target.Name + "`. Do not edit by hand.\n\n")
	body.WriteString("## Run order\n\n")
	body.WriteString("```bash\n")
	body.WriteString("# 1. Provision AWS resources.\n")
	body.WriteString("tofu -chdir=" + repoRelativeOutDir + " init\n")
	body.WriteString("tofu -chdir=" + repoRelativeOutDir + " plan        # human-review\n")
	body.WriteString("tofu -chdir=" + repoRelativeOutDir + " apply\n\n")
	body.WriteString("# 2. Capture tofu outputs into a per-developer .env.\n")
	body.WriteString("(cd " + repoRelativeOutDir + " && " + envCmd + ")\n\n")
	body.WriteString("# 3. Bring the local containers up; they auth to real AWS via ~/.aws.\n")
	body.WriteString("docker compose \\\n")
	body.WriteString("  -f infra/docker-compose.yaml \\\n")
	body.WriteString("  -f " + repoRelativeOutDir + "/docker-compose.override.generated.yaml \\\n")
	body.WriteString("  --env-file " + repoRelativeOutDir + "/.env.hybrid \\\n")
	body.WriteString("  --profile app up\n")
	body.WriteString("```\n\n")
	body.WriteString("## Teardown\n\n")
	body.WriteString("```bash\n")
	body.WriteString("docker compose ... down\n")
	body.WriteString("tofu -chdir=" + repoRelativeOutDir + " destroy\n")
	body.WriteString("```\n\n")
	body.WriteString("## Security note\n\n")
	body.WriteString("RDS + ElastiCache are emitted with `publicly_accessible = true`, locked down by a security group that allows ingress only from your laptop's current public IP (`data.http.myip`). If your IP changes mid-session, re-run `tofu apply` to refresh the SG.\n\n")
	body.WriteString("This is **dev-only**. M4b introduces a real VPC; production never exposes RDS/ElastiCache publicly.\n")

	path := filepath.Join(outDir, "README.md")
	if err := os.WriteFile(path, []byte(body.String()), 0o644); err != nil {
		return "", fmt.Errorf("EmitHybridReadme write: %w", err)
	}
	return path, nil
}

// EmitFargateReadme writes a README.md for Fargate targets describing
// the two-phase caravan workflow: `caravan compile` emits HCL (user may
// hand-edit before deploying); `caravan up` pushes images and runs tofu
// apply against the on-disk HCL; `caravan down` runs tofu destroy. The
// user never types a tofu command directly — caravan owns the
// invocation — but tofu's interactive plan + confirmation step is
// preserved.
func EmitFargateReadme(rp *compiler.ResolvedPlan, outDir, repoRelativeOutDir string) (string, error) {
	if rp == nil || rp.Plan == nil {
		return "", fmt.Errorf("nil ResolvedPlan")
	}
	target := rp.Plan.Targets[rp.TargetName]
	if target == nil || target.Runtime != compiler.RuntimeFargate {
		return "", nil
	}

	repoRelativeOutDir = filepath.ToSlash(repoRelativeOutDir)

	// Sorted entry names for the pre-create checklist (deterministic).
	entries := make([]string, 0)
	for name, mode := range target.Entries {
		if mode == compiler.EntryContainer {
			entries = append(entries, name)
		}
	}
	sort.Strings(entries)

	var body strings.Builder
	body.WriteString("# Caravan Fargate target — " + rp.Plan.Name + " / " + target.Name + "\n\n")
	body.WriteString("Generated by `caravan compile --target=" + target.Name + "`. Do not edit this README by hand — re-emit it instead.\n\n")
	body.WriteString("## Prereqs (one-time per AWS account)\n\n")
	body.WriteString("Create the ECR repositories that hold each entry's container image. Per the M4-cloud-prereq onboarding checklist (`docs/aws_onboarding_checklist.md`), one repo per entry-image:\n\n")
	body.WriteString("```bash\n")
	for _, name := range entries {
		body.WriteString("aws ecr create-repository --repository-name " + dashedReadmeName(name))
		body.WriteString(" --region " + target.Region + " --profile " + target.AwsProfile + "\n")
	}
	body.WriteString("```\n\n")
	body.WriteString("## Deploy\n\n")
	body.WriteString("```bash\n")
	body.WriteString("# 1. (Already done — these files are the output.)\n")
	body.WriteString("caravan compile --target=" + target.Name + "\n\n")
	body.WriteString("# 2. (Optional.) Review or hand-edit the emitted HCL in\n")
	body.WriteString("#    " + repoRelativeOutDir + "/ — your edits survive caravan up.\n\n")
	body.WriteString("# 3. Build + push images to ECR, then tofu apply.\n")
	body.WriteString("#    Caravan owns the tofu invocation; tofu's interactive\n")
	body.WriteString("#    plan + confirmation step is preserved.\n")
	body.WriteString("caravan up --target=" + target.Name + "\n\n")
	body.WriteString("# 4. Verify tasks are RUNNING.\n")
	body.WriteString("aws ecs list-tasks --cluster " + target.ECSClusterName + " \\\n")
	body.WriteString("  --region " + target.Region + " --profile " + target.AwsProfile + "\n")
	body.WriteString("```\n\n")
	body.WriteString("## Teardown\n\n")
	body.WriteString("Fargate tasks + NAT gateway accrue cost while running. Tear down promptly when done:\n\n")
	body.WriteString("```bash\n")
	body.WriteString("caravan down --target=" + target.Name + "\n")
	body.WriteString("```\n\n")
	body.WriteString("ECR images persist across `caravan down` (different lifecycle) — they're re-used on the next `caravan up`. Delete the repos manually if you want a fresh start.\n\n")
	body.WriteString("## What's inside\n\n")
	body.WriteString("- `main.tf` — VPC + 2-AZ subnets + IGW + single NAT + tasks SG; ECS cluster; Cloud Map private DNS namespace `" + target.CloudMapNamespace + "`; per-entry task def + ECS service; per-seam Cloud Map service (Fargate-Fargate RPC routes through Cloud Map DNS).\n")
	body.WriteString("- `iam.tf` — per-entry Fargate task roles + execution role with the AWS-managed `AmazonECSTaskExecutionRolePolicy`.\n")
	body.WriteString("- `backend.tf` / `versions.tf` — remote state on S3+DynamoDB, AWS provider pin.\n\n")
	body.WriteString("Hand-edits to these files are preserved by `caravan up` (it only re-emits when you run `caravan compile`). Edit boldly; re-emit when you want caravan's view back.\n")

	path := filepath.Join(outDir, "README.md")
	if err := os.WriteFile(path, []byte(body.String()), 0o644); err != nil {
		return "", fmt.Errorf("EmitFargateReadme write: %w", err)
	}
	return path, nil
}

// dashedReadmeName mirrors the ECR repo naming used by the HCL emitter
// (toDashed of the entry name) so the README's `aws ecr create-repository`
// commands match the data lookups in main.tf exactly.
func dashedReadmeName(s string) string {
	s = strings.ToLower(s)
	return strings.ReplaceAll(s, "_", "-")
}
