package emit

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/paulxiep/caravan/internal/compiler"
)

// EmitEnvTemplate writes a `.env.template` next to the HCL files. The
// template names every variable the user must populate before
// `docker compose up`, with the matching `tofu output -json | jq -r ...`
// snippet inline so the user can copy/paste.
//
// One-shot dance from the template (also documented in README.md):
//
//	tofu -chdir=<outDir> output -json |
//	  jq -r 'to_entries | map("\(.key)=\(.value.value)") | .[]' > <outDir>/.env.hybrid
//	docker compose ... --env-file <outDir>/.env.hybrid up
//
// Only fires for hybrid-dev targets. Returns the path written.
func EmitEnvTemplate(rp *compiler.ResolvedPlan, outDir string) (string, error) {
	if rp == nil || rp.Plan == nil {
		return "", fmt.Errorf("nil ResolvedPlan")
	}
	target := rp.Plan.Targets[rp.TargetName]
	if target == nil || !target.CredsPassthrough {
		return "", nil
	}

	// Collect all unique env var keys that consumer entries see via
	// resource_endpoint vars. These are the keys the compose override
	// references as `${VAR}` — they must end up in the .env file.
	keys := map[string]struct{}{}
	for _, env := range rp.ResourceEnvVars {
		for k, v := range env {
			if strings.HasPrefix(v, "${") {
				keys[k] = struct{}{}
			}
		}
	}
	if len(keys) == 0 {
		return "", nil
	}
	sorted := make([]string, 0, len(keys))
	for k := range keys {
		sorted = append(sorted, k)
	}
	sort.Strings(sorted)

	var body strings.Builder
	body.WriteString("# Generated by `caravan compile --target=" + target.Name + "`. Do not commit.\n")
	body.WriteString("# Populate by running:\n")
	body.WriteString("#\n")
	body.WriteString("#   tofu -chdir=. output -json | \\\n")
	body.WriteString("#     jq -r 'to_entries | map(\"\\(.key)=\\(.value.value)\") | .[]' > .env.hybrid\n")
	body.WriteString("#\n")
	body.WriteString("# then layer the compose override with `--env-file .env.hybrid`.\n\n")
	for _, k := range sorted {
		body.WriteString(k)
		body.WriteString("=\n")
	}

	path := filepath.Join(outDir, ".env.template")
	if err := os.WriteFile(path, []byte(body.String()), 0o644); err != nil {
		return "", fmt.Errorf("EmitEnvTemplate write: %w", err)
	}
	return path, nil
}

// EmitHybridReadme writes a README.md in outDir with the 3-step run
// instructions for hybrid-dev mode. Lands next to the generated HCL +
// compose override so the user finds it when they cd into outDir.
func EmitHybridReadme(rp *compiler.ResolvedPlan, outDir, repoRelativeOutDir string) (string, error) {
	if rp == nil || rp.Plan == nil {
		return "", fmt.Errorf("nil ResolvedPlan")
	}
	target := rp.Plan.Targets[rp.TargetName]
	if target == nil || !target.CredsPassthrough {
		return "", nil
	}

	envCmd := "tofu -chdir=. output -json | \\\n" +
		"  jq -r 'to_entries | map(\"\\(.key)=\\(.value.value)\") | .[]' > .env.hybrid"

	// The README is read by humans running shell commands; emit forward
	// slashes for cross-shell compatibility (Windows native `\` breaks
	// bash / Git Bash quoting on Windows).
	repoRelativeOutDir = filepath.ToSlash(repoRelativeOutDir)

	var body strings.Builder
	body.WriteString("# Caravan hybrid-dev target — " + rp.Plan.Name + " / " + target.Name + "\n\n")
	body.WriteString("Generated by `caravan compile --target=" + target.Name + "`. Do not edit by hand.\n\n")
	body.WriteString("## Run order\n\n")
	body.WriteString("```bash\n")
	body.WriteString("# 1. Provision AWS resources.\n")
	body.WriteString("tofu -chdir=" + repoRelativeOutDir + " init\n")
	body.WriteString("tofu -chdir=" + repoRelativeOutDir + " plan        # human-review\n")
	body.WriteString("tofu -chdir=" + repoRelativeOutDir + " apply\n\n")
	body.WriteString("# 2. Capture tofu outputs into a per-developer .env.\n")
	body.WriteString("(cd " + repoRelativeOutDir + " && " + envCmd + ")\n\n")
	body.WriteString("# 3. Bring the local containers up; they auth to real AWS via ~/.aws.\n")
	body.WriteString("docker compose \\\n")
	body.WriteString("  -f infra/docker-compose.yaml \\\n")
	body.WriteString("  -f " + repoRelativeOutDir + "/docker-compose.override.generated.yaml \\\n")
	body.WriteString("  --env-file " + repoRelativeOutDir + "/.env.hybrid \\\n")
	body.WriteString("  --profile app up\n")
	body.WriteString("```\n\n")
	body.WriteString("## Teardown\n\n")
	body.WriteString("```bash\n")
	body.WriteString("docker compose ... down\n")
	body.WriteString("tofu -chdir=" + repoRelativeOutDir + " destroy\n")
	body.WriteString("```\n\n")
	body.WriteString("## Security note\n\n")
	body.WriteString("RDS + ElastiCache are emitted with `publicly_accessible = true`, locked down by a security group that allows ingress only from your laptop's current public IP (`data.http.myip`). If your IP changes mid-session, re-run `tofu apply` to refresh the SG.\n\n")
	body.WriteString("This is **dev-only**. M4b introduces a real VPC; production never exposes RDS/ElastiCache publicly.\n")

	path := filepath.Join(outDir, "README.md")
	if err := os.WriteFile(path, []byte(body.String()), 0o644); err != nil {
		return "", fmt.Errorf("EmitHybridReadme write: %w", err)
	}
	return path, nil
}
